version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: shoo1001/equipment-borrow-system:latest
    container_name: g04_app
    networks:
      - course_proxy
      - appnetwork
    ports:
      - "3004:3000"
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    container_name: g04_db
    networks:
      - appnetwork
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wab_borrow_return
    ports:
      - "3304:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
networks:
  course_proxy:
    driver: bridge
  appnetwork:
    driver: bridge
